### PR TITLE
periodic mesh

### PR DESCRIPTION
**Pull request by simbilod**
First quick hack to achieve #6 ; see below for caveats

Example:

```
    left_wall_up = LineString([(-width_wg_2-1, -2),(-width_wg_2-1, 6)])
    right_wall_up = LineString([(width_wg_2-0.5, -2),(width_wg_2-0.5, 6)])
    left_wall_dw = LineString([(-width_wg_2-1, -6),(-width_wg_2-1, -2)])
    right_wall_dw = LineString([(width_wg_2-0.5, -6),(width_wg_2-0.5, -2)])

    polygons = OrderedDict(
        left_wall_up=left_wall_up,
        right_wall_up=right_wall_up,
        left_wall_dw=left_wall_dw,
        right_wall_dw=right_wall_dw,
        source=source,
        core=core,
        box=box,
    )

[...]

    mesh = mesh_from_OrderedDict(
        polygons, 
        resolutions, 
        filename="mesh.msh", 
        default_resolution_max=1,
        periodic_lines=[("left_wall_up", "right_wall_up")],
    )
```

See the left up and right up walls have matching nodes, but not the bottom ones:

image

There are currently NO CHECKS, you need to make sure that 
- at the meshing stage (after all intersections have been taken) that the lines you want to be periodic exactly map to how they are inserted into the geometry (so make them high mesh order).
- the lines that are made periodic must be parallel and of the same length; in fact, the translation vector is computed from the position of their first node, so they need to be drawn the same way too

Eventually we can add checks for this and more logic to handle intersection geometries with periodic walls

### CODE REVIEW

**Comment by simbilod** [comment]
I think precommit didn't run

**Comment by HelgeGehring** [comment]
Awesome, thanks!

about pre-commit: just run `pre-commit install` and modify a tiny thing in the file, than it should be reformatted

**Comment by simbilod** [comment]
hmmm I'm getting errors with the poetry version. I can try to fix later

**Comment by HelgeGehring** [comment]
Fixed the formatting!

**Pull request merged**
