### PR TITLE
Fix cylindrical mode solver (signs + H-field calculations)

### PR DESCRIPTION
**Pull request by lucasgrjn**
The present commit solves the issues associated with the Julia cylindrical mode solver

- Correct the $2\pi$-factor in the defenition of $\omega$ in the mode-solver.
- The signs of the H-fields calculated from the E-fields are corrected for both the cylindrical and non-cylindrical mode solver.
- Julia bend solver examples were updated by considering a 3-order PML (in order to obtain a 2-order PML after derivation of the function as presented in _Jedidi, Rym, and Roger Pierre. "High-order finite-element methods for the computation of bending loss in optical waveguides." Journal of Lightwave Technology 25.9 (2007): 2618-2630._)

### CODE REVIEW

**Comment by HelgeGehring** [comment]
looks good, thanks!
i think it would be good to remove in the examples the pml_y (i.e. set it to 0) to be consistent with the paper, right?

**Comment by HelgeGehring** [comment]
Thanks!

**Comment by lucasgrjn** [comment]
Julia Formatter should work now!

**Comment by HelgeGehring** [comment]
Yay, thanks!

**Pull request merged**
